# 创建用户表
CREATE TABLE cc_user_0 (
id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
login_name VARCHAR(20) NOT NULL DEFAULT '' COMMENT '登陆用户名',
real_name VARCHAR(20) NOT NULL DEFAULT '' COMMENT '昵称',
password CHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
email VARCHAR(50) NOT NULL DEFAULT '' COMMENT '邮箱',
status TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0正常 -1禁用',
create_time INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
update_time INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间',
UNIQUE KEY `idx_login_name` (`login_name`)
)ENGINE=INNODB CHARSET=utf8;



